package com.website.service.entity;

public class SongComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_comment.id
     *
     * @mbggenerated Fri Aug 07 15:50:58 GMT+08:00 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_comment.song_id
     *
     * @mbggenerated Fri Aug 07 15:50:58 GMT+08:00 2020
     */
    private String songId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_comment.content
     *
     * @mbggenerated Fri Aug 07 15:50:58 GMT+08:00 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_comment.like_count
     *
     * @mbggenerated Fri Aug 07 15:50:58 GMT+08:00 2020
     */
    private String likeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_comment.create_time
     *
     * @mbggenerated Fri Aug 07 15:50:58 GMT+08:00 2020
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_comment.user_img
     *
     * @mbggenerated Fri Aug 07 15:50:58 GMT+08:00 2020
     */
    private String userImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_comment.user_name
     *
     * @mbggenerated Fri Aug 07 15:50:58 GMT+08:00 2020
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_comment.id
     *
     * @return the value of song_comment.id
     *
     * @mbggenerated Fri Aug 07 15:50:58 GMT+08:00 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_comment.id
     *
     * @param id the value for song_comment.id
     *
     * @mbggenerated Fri Aug 07 15:50:58 GMT+08:00 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_comment.song_id
     *
     * @return the value of song_comment.song_id
     *
     * @mbggenerated Fri Aug 07 15:50:58 GMT+08:00 2020
     */
    public String getSongId() {
        return songId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_comment.song_id
     *
     * @param songId the value for song_comment.song_id
     *
     * @mbggenerated Fri Aug 07 15:50:58 GMT+08:00 2020
     */
    public void setSongId(String songId) {
        this.songId = songId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_comment.content
     *
     * @return the value of song_comment.content
     *
     * @mbggenerated Fri Aug 07 15:50:58 GMT+08:00 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_comment.content
     *
     * @param content the value for song_comment.content
     *
     * @mbggenerated Fri Aug 07 15:50:58 GMT+08:00 2020
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_comment.like_count
     *
     * @return the value of song_comment.like_count
     *
     * @mbggenerated Fri Aug 07 15:50:58 GMT+08:00 2020
     */
    public String getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_comment.like_count
     *
     * @param likeCount the value for song_comment.like_count
     *
     * @mbggenerated Fri Aug 07 15:50:58 GMT+08:00 2020
     */
    public void setLikeCount(String likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_comment.create_time
     *
     * @return the value of song_comment.create_time
     *
     * @mbggenerated Fri Aug 07 15:50:58 GMT+08:00 2020
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_comment.create_time
     *
     * @param createTime the value for song_comment.create_time
     *
     * @mbggenerated Fri Aug 07 15:50:58 GMT+08:00 2020
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_comment.user_img
     *
     * @return the value of song_comment.user_img
     *
     * @mbggenerated Fri Aug 07 15:50:58 GMT+08:00 2020
     */
    public String getUserImg() {
        return userImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_comment.user_img
     *
     * @param userImg the value for song_comment.user_img
     *
     * @mbggenerated Fri Aug 07 15:50:58 GMT+08:00 2020
     */
    public void setUserImg(String userImg) {
        this.userImg = userImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_comment.user_name
     *
     * @return the value of song_comment.user_name
     *
     * @mbggenerated Fri Aug 07 15:50:58 GMT+08:00 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_comment.user_name
     *
     * @param userName the value for song_comment.user_name
     *
     * @mbggenerated Fri Aug 07 15:50:58 GMT+08:00 2020
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }
}