package com.website.service.entity.weibo;

import java.util.ArrayList;
import java.util.Arrays;

public class WeiboSendList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEIBO_SEND_LIST.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEIBO_SEND_LIST.USER_ID
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEIBO_SEND_LIST.USER_MAIL
     *
     * @mbg.generated
     */
    private String userMail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEIBO_SEND_LIST.WEIBO_ID
     *
     * @mbg.generated
     */
    private String weiboId;

    private String weiboName;


    public String getWeiboName() {
        return weiboName;
    }

    public void setWeiboName(String weiboName) {
        this.weiboName = weiboName;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEIBO_SEND_LIST.SEND_SWITCH
     *
     * @mbg.generated
     */
    private String sendSwitch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEIBO_SEND_LIST.CREATE_TIME
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEIBO_SEND_LIST.UPDATE_TIME
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEIBO_SEND_LIST.ID
     *
     * @return the value of WEIBO_SEND_LIST.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEIBO_SEND_LIST.ID
     *
     * @param id the value for WEIBO_SEND_LIST.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEIBO_SEND_LIST.USER_ID
     *
     * @return the value of WEIBO_SEND_LIST.USER_ID
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEIBO_SEND_LIST.USER_ID
     *
     * @param userId the value for WEIBO_SEND_LIST.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEIBO_SEND_LIST.USER_MAIL
     *
     * @return the value of WEIBO_SEND_LIST.USER_MAIL
     *
     * @mbg.generated
     */
    public String getUserMail() {
        return userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEIBO_SEND_LIST.USER_MAIL
     *
     * @param userMail the value for WEIBO_SEND_LIST.USER_MAIL
     *
     * @mbg.generated
     */
    public void setUserMail(String userMail) {
        this.userMail = userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEIBO_SEND_LIST.WEIBO_ID
     *
     * @return the value of WEIBO_SEND_LIST.WEIBO_ID
     *
     * @mbg.generated
     */
    public String getWeiboId() {
        return weiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEIBO_SEND_LIST.WEIBO_ID
     *
     * @param weiboId the value for WEIBO_SEND_LIST.WEIBO_ID
     *
     * @mbg.generated
     */
    public void setWeiboId(String weiboId) {
        this.weiboId = weiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEIBO_SEND_LIST.SEND_SWITCH
     *
     * @return the value of WEIBO_SEND_LIST.SEND_SWITCH
     *
     * @mbg.generated
     */
    public String getSendSwitch() {
        return sendSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEIBO_SEND_LIST.SEND_SWITCH
     *
     * @param sendSwitch the value for WEIBO_SEND_LIST.SEND_SWITCH
     *
     * @mbg.generated
     */
    public void setSendSwitch(String sendSwitch) {
        this.sendSwitch = sendSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEIBO_SEND_LIST.CREATE_TIME
     *
     * @return the value of WEIBO_SEND_LIST.CREATE_TIME
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEIBO_SEND_LIST.CREATE_TIME
     *
     * @param createTime the value for WEIBO_SEND_LIST.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEIBO_SEND_LIST.UPDATE_TIME
     *
     * @return the value of WEIBO_SEND_LIST.UPDATE_TIME
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEIBO_SEND_LIST.UPDATE_TIME
     *
     * @param updateTime the value for WEIBO_SEND_LIST.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEIBO_SEND_LIST
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", userMail=").append(userMail);
        sb.append(", weiboId=").append(weiboId);
        sb.append(", sendSwitch=").append(sendSwitch);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEIBO_SEND_LIST
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WeiboSendList other = (WeiboSendList) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserMail() == null ? other.getUserMail() == null : this.getUserMail().equals(other.getUserMail()))
            && (this.getWeiboId() == null ? other.getWeiboId() == null : this.getWeiboId().equals(other.getWeiboId()))
            && (this.getSendSwitch() == null ? other.getSendSwitch() == null : this.getSendSwitch().equals(other.getSendSwitch()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEIBO_SEND_LIST
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserMail() == null) ? 0 : getUserMail().hashCode());
        result = prime * result + ((getWeiboId() == null) ? 0 : getWeiboId().hashCode());
        result = prime * result + ((getSendSwitch() == null) ? 0 : getSendSwitch().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table WEIBO_SEND_LIST
     *
     * @mbg.generated
     */
    public enum Column {
        id("ID", "id", "VARCHAR", false),
        userId("USER_ID", "userId", "VARCHAR", false),
        userMail("USER_MAIL", "userMail", "VARCHAR", false),
        weiboId("WEIBO_ID", "weiboId", "VARCHAR", false),
        sendSwitch("SEND_SWITCH", "sendSwitch", "VARCHAR", false),
        createTime("CREATE_TIME", "createTime", "VARCHAR", false),
        updateTime("UPDATE_TIME", "updateTime", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table WEIBO_SEND_LIST
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table WEIBO_SEND_LIST
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table WEIBO_SEND_LIST
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table WEIBO_SEND_LIST
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table WEIBO_SEND_LIST
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table WEIBO_SEND_LIST
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table WEIBO_SEND_LIST
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table WEIBO_SEND_LIST
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table WEIBO_SEND_LIST
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table WEIBO_SEND_LIST
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table WEIBO_SEND_LIST
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table WEIBO_SEND_LIST
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table WEIBO_SEND_LIST
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table WEIBO_SEND_LIST
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table WEIBO_SEND_LIST
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table WEIBO_SEND_LIST
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}
