package com.website.service.mapper;


import java.util.List;

import com.website.service.entity.MailRecord;
import com.website.service.entity.MailRecordExample;
import org.apache.ibatis.annotations.Param;

public interface MailRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAIL_RECORD
     *
     * @mbg.generated
     */
    long countByExample(MailRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAIL_RECORD
     *
     * @mbg.generated
     */
    int deleteByExample(MailRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAIL_RECORD
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAIL_RECORD
     *
     * @mbg.generated
     */
    int insert(MailRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAIL_RECORD
     *
     * @mbg.generated
     */
    int insertSelective(MailRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAIL_RECORD
     *
     * @mbg.generated
     */
    MailRecord selectOneByExample(MailRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAIL_RECORD
     *
     * @mbg.generated
     */
    MailRecord selectOneByExampleSelective(@Param("example") MailRecordExample example, @Param("selective") MailRecord.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAIL_RECORD
     *
     * @mbg.generated
     */
    MailRecord selectOneByExampleWithBLOBs(MailRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAIL_RECORD
     *
     * @mbg.generated
     */
    List<MailRecord> selectByExampleSelective(@Param("example") MailRecordExample example, @Param("selective") MailRecord.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAIL_RECORD
     *
     * @mbg.generated
     */
    List<MailRecord> selectByExampleWithBLOBs(MailRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAIL_RECORD
     *
     * @mbg.generated
     */
    List<MailRecord> selectByExample(MailRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAIL_RECORD
     *
     * @mbg.generated
     */
    MailRecord selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") MailRecord.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAIL_RECORD
     *
     * @mbg.generated
     */
    MailRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAIL_RECORD
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MailRecord record, @Param("example") MailRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAIL_RECORD
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") MailRecord record, @Param("example") MailRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAIL_RECORD
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MailRecord record, @Param("example") MailRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAIL_RECORD
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MailRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAIL_RECORD
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(MailRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAIL_RECORD
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MailRecord record);
}
