package com.website.service.mapper;

import com.website.service.entity.SongInfo;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SongListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbggenerated Fri Aug 07 11:50:42 GMT+08:00 2020
     */
    int deleteByPrimaryKey(@Param("id") String id, @Param("songId") String songId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbggenerated Fri Aug 07 11:50:42 GMT+08:00 2020
     */
    int insert(SongInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbggenerated Fri Aug 07 11:50:42 GMT+08:00 2020
     */
    SongInfo selectByPrimaryKey(@Param("id") String id, @Param("songId") String songId);


    SongInfo selectBySongId(String songId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbggenerated Fri Aug 07 11:50:42 GMT+08:00 2020
     */
    List<SongInfo> selectAll();

    List<SongInfo> selectAllNoCraw();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbggenerated Fri Aug 07 11:50:42 GMT+08:00 2020
     */
    int updateByPrimaryKey(SongInfo record);
}