package com.website.service.mapper.weibo;

import com.website.service.entity.weibo.WeiboUserNews;
import com.website.service.entity.weibo.WeiboUserNewsExample;
import com.website.service.entity.weibo.WeiboUserNewsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeiboUserNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEIBO_USER_NEWS
     *
     * @mbg.generated
     */
    long countByExample(WeiboUserNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEIBO_USER_NEWS
     *
     * @mbg.generated
     */
    int deleteByExample(WeiboUserNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEIBO_USER_NEWS
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEIBO_USER_NEWS
     *
     * @mbg.generated
     */
    int insert(WeiboUserNewsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEIBO_USER_NEWS
     *
     * @mbg.generated
     */
    int insertSelective(WeiboUserNewsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEIBO_USER_NEWS
     *
     * @mbg.generated
     */
    WeiboUserNews selectOneByExample(WeiboUserNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEIBO_USER_NEWS
     *
     * @mbg.generated
     */
    WeiboUserNewsWithBLOBs selectOneByExampleSelective(@Param("example") WeiboUserNewsExample example, @Param("selective") WeiboUserNewsWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEIBO_USER_NEWS
     *
     * @mbg.generated
     */
    WeiboUserNewsWithBLOBs selectOneByExampleWithBLOBs(WeiboUserNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEIBO_USER_NEWS
     *
     * @mbg.generated
     */
    List<WeiboUserNewsWithBLOBs> selectByExampleSelective(@Param("example") WeiboUserNewsExample example, @Param("selective") WeiboUserNewsWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEIBO_USER_NEWS
     *
     * @mbg.generated
     */
    List<WeiboUserNewsWithBLOBs> selectByExampleWithBLOBs(WeiboUserNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEIBO_USER_NEWS
     *
     * @mbg.generated
     */
    List<WeiboUserNews> selectByExample(WeiboUserNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEIBO_USER_NEWS
     *
     * @mbg.generated
     */
    WeiboUserNewsWithBLOBs selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") WeiboUserNewsWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEIBO_USER_NEWS
     *
     * @mbg.generated
     */
    WeiboUserNewsWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEIBO_USER_NEWS
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WeiboUserNewsWithBLOBs record, @Param("example") WeiboUserNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEIBO_USER_NEWS
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") WeiboUserNewsWithBLOBs record, @Param("example") WeiboUserNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEIBO_USER_NEWS
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WeiboUserNews record, @Param("example") WeiboUserNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEIBO_USER_NEWS
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WeiboUserNewsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEIBO_USER_NEWS
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(WeiboUserNewsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEIBO_USER_NEWS
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WeiboUserNews record);
}