package com.website.service.mapper.system;

import com.website.service.entity.system.SysNotice;
import com.website.service.entity.system.SysNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE
     *
     * @mbg.generated
     */
    long countByExample(SysNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE
     *
     * @mbg.generated
     */
    int deleteByExample(SysNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE
     *
     * @mbg.generated
     */
    int insert(SysNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE
     *
     * @mbg.generated
     */
    int insertSelective(SysNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE
     *
     * @mbg.generated
     */
    SysNotice selectOneByExample(SysNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE
     *
     * @mbg.generated
     */
    SysNotice selectOneByExampleSelective(@Param("example") SysNoticeExample example, @Param("selective") SysNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE
     *
     * @mbg.generated
     */
    List<SysNotice> selectByExampleSelective(@Param("example") SysNoticeExample example, @Param("selective") SysNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE
     *
     * @mbg.generated
     */
    List<SysNotice> selectByExample(SysNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE
     *
     * @mbg.generated
     */
    SysNotice selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SysNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE
     *
     * @mbg.generated
     */
    SysNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE
     *
     * @mbg.generated
     */
    SysNotice selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysNotice record, @Param("example") SysNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysNotice record, @Param("example") SysNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SysNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}