package com.website.service.mapper.system;

import com.website.service.entity.system.SysNoticeAdmin;
import com.website.service.entity.system.SysNoticeAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysNoticeAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE_ADMIN
     *
     * @mbg.generated
     */
    long countByExample(SysNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE_ADMIN
     *
     * @mbg.generated
     */
    int deleteByExample(SysNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE_ADMIN
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE_ADMIN
     *
     * @mbg.generated
     */
    int insert(SysNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE_ADMIN
     *
     * @mbg.generated
     */
    int insertSelective(SysNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE_ADMIN
     *
     * @mbg.generated
     */
    SysNoticeAdmin selectOneByExample(SysNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE_ADMIN
     *
     * @mbg.generated
     */
    SysNoticeAdmin selectOneByExampleSelective(@Param("example") SysNoticeAdminExample example, @Param("selective") SysNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE_ADMIN
     *
     * @mbg.generated
     */
    List<SysNoticeAdmin> selectByExampleSelective(@Param("example") SysNoticeAdminExample example, @Param("selective") SysNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE_ADMIN
     *
     * @mbg.generated
     */
    List<SysNoticeAdmin> selectByExample(SysNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE_ADMIN
     *
     * @mbg.generated
     */
    SysNoticeAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SysNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE_ADMIN
     *
     * @mbg.generated
     */
    SysNoticeAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE_ADMIN
     *
     * @mbg.generated
     */
    SysNoticeAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE_ADMIN
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysNoticeAdmin record, @Param("example") SysNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE_ADMIN
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysNoticeAdmin record, @Param("example") SysNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE_ADMIN
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE_ADMIN
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE_ADMIN
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SysNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_NOTICE_ADMIN
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}